spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: username
    password: Laoyang456!
    url: jdbc:mysql://127.0.0.1/blog?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /blog3